name: Terraform CI

on:
workflow_call:
  inputs:
    working-directory:
      type: string
      default: "."
    TOOGLE_DEV:
      type: boolean
      default: false
    Toogle_qs:
      type: boolean
      default: false
    TOOGLE_PROD:
      type: boolean
      default: false

runs:
  jobs:
    - terraform-pre-plan:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      steps:
        - name: terraform-init
          uses: ./.github/terraform-github-actions/actions/terraform-init
        - name: terraform-validate
          if: ${{ env.TOOGLE_DEV == true }}
          uses: ./.github/terraform-github-actions/actions/terraform-validate
          with:
            workspace: dev
        - name: terraform-validate-in-default
          if: ${{ env.TOOGLE_DEV != true }}
          uses: ./.github/terraform-github-actions/actions/terraform-validate

    - terraform-plan-pr:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      steps:
        - name: login
          uses: ./.github/terraform-github-actions/actions/terraform-login
        - name: plan
          if: ${{ env.TOOGLE_DEV == true }}
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: dev
        - name: plan
          if: ${{ env.TOOGLE_QS == true }}
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: qs
        - name: plan
          if: ${{ env.TOOGLE_PROD == true }}
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: prod

    - terraform-apply:
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
      runs-on: ubuntu-latest
      steps:
        - name: plan-dev
          if: ${{ env.TOOGLE_DEV == true }}
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: dev
        - name: plan-qs
          if: ${{ env.TOOGLE_QS == true }}
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: qs
        - name: plan-prod
          if: ${{ env.TOOGLE_PROD == true }}
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: prod
        - name: apply-dev
          if: (${{ env.TOOGLE_DEV == true }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: dev
        - name: apply-qs
          if: (${{ env.TOOGLE_qs == true }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: qs
        - name: apply-prod
          if: (${{ env.TOOGLE_PROD == true }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: prod
