name: Terraform CI

on:
workflow_call:
  inputs:
    working-directory:
      type: string
      default: src
    TOOGLE_DEV:
      type: boolean
      default: false
    Toogle_QA:
      type: boolean
      default: false
    TOOGLE_PROD:
      type: boolean
      default: false

runs:
  jobs:
    - terraform-validate:
      runs-on: ubuntu-latest
      uses: ./.github/terraform-github-actions/actions/terraform-validate
      with:
        workspace: dev
    - terraform-plan-dev:
      steps:
        - name: plan
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: dev
        - name: apply
          if: ${{ github.workspace != 'dev' }} || (github.event_name == 'push' && github.ref == 'refs/heads/main') && (${{ env.TOOGLE_DEV == 'true' }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: dev
    - terraform-plan-qa:
      if: ${{ env.TOOGLE_QA == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: plan
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: qa
        - name: apply
          if: ${{ github.workspace != 'qa' }} || (github.event_name == 'push' && github.ref == 'refs/heads/main') && (${{ env.TOOGLE_QA == 'true' }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: qa
    - terraform-prod:
      if: ${{ env.TOOGLE_PROD == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: plan
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: prod
        - name: apply
          if: ${{ github.workspace != 'prod' }} || (github.event_name == 'push' && github.ref == 'refs/heads/main') && (${{ env.TOOGLE_PROD == 'true' }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: prod
