name: Terraform CI

on:
workflow_call:
  inputs:
    working-directory:
      type: string
      default: "."
    TOOGLE_DEV:
      type: boolean
      default: false
    Toogle_QA:
      type: boolean
      default: false
    TOOGLE_PROD:
      type: boolean
      default: false

runs:
  jobs:
    - terraform-pre-plan:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      steps:
        - name: terraform-init
          uses: ./.github/terraform-github-actions/actions/terraform-init
        - name: terraform-validate
          uses: ./.github/terraform-github-actions/actions/terraform-validate
          with:
            workspace: dev

    - terraform-plan-dev:
      runs-on: ubuntu-latest
      if: github.event == 'pull_request' && (${{ env.TOOGLE_DEV == 'true' }}
      steps:
        - name: plan
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: dev

    - terraform-apply-dev:
      runs-on: ubuntu-latest
      steps:
        - name: apply
          if: (github.event_name == 'push' && github.ref == 'refs/heads/main') && (${{ env.TOOGLE_DEV == 'true' }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: dev

    - terraform-plan-qa:
      if: github.event == 'pull_request' && (${{ env.TOOGLE_QS == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: plan
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: qa

    - terraform-apply-qa:
      if: github.event == 'pull_request' && (${{ env.TOOGLE_QS == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: apply
          if: ${{ github.workspace != 'qa' }} || (github.event_name == 'push' && github.ref == 'refs/heads/main') && (${{ env.TOOGLE_QA == 'true' }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: qa

    - terraform-plan-prod:
      if: github.event == 'pull_request' && ${{ env.TOOGLE_PROD == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: plan
          uses: ./.github/terraform-github-actions/actions/terraform-plan
          with:
            workspace: prod
        - name: apply
          if: ${{ github.workspace != 'prod' }} || (github.event_name == 'push' && github.ref == 'refs/heads/main') && (${{ env.TOOGLE_PROD == 'true' }})
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: prod

    - terraform-plan-prod:
      if: ${{ github.workspace != 'prod' }} || (github.event_name == 'push' && github.ref == 'refs/heads/main') && (${{ env.TOOGLE_PROD == 'true' }})
      runs-on: ubuntu-latest
      steps:
        - name: apply
          uses: ./.github/terraform-github-actions/actions/terraform-apply
          with:
            workspace: prod
