name: 'Create a new releasae'

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bump version and push tag
      id: create_tag
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: main
        CUSTOM_TAG: ${{ github.event.head_commit.message }}
        TAG_CONTEXT: commit
        DRY_RUN: false
        VERBOSE: true

    - name: Fix permissions
      run: sudo chown -R $(whoami) .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: Release ${{ steps.create_tag.outputs.tag }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false