name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      TOOGLE_DEV:
        type: boolean
        default: false
      Toogle_qs:
        type: boolean
        default: false
      TOOGLE_PROD:
        type: boolean
        default: false

jobs:
  terraform-pre-plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: login
        uses: ./.github/workflows/terraform-login
      - name: terraform-init
        uses: ./.github/workflows/terraform-init
      - name: terraform-validate
        if: ${{ github.event.inputs.TOOGLE_DEV == true }}
        uses: ./.github/workflows/terraform-validate
        with:
          workspace: dev
      - name: terraform-validate-in-default
        if: ${{ github.event.inputs.TOOGLE_DEV != true }}
        uses: ./.github/workflows/terraform-validate
  terraform-plan-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: login
        uses: ./.github/workflows/terraform-login
      - name: plan
        if: ${{ github.event.inputs.TOOGLE_DEV == true }}
        uses: ./.github/workflows/terraform-plan
        with:
          workspace: dev
      - name: plan
        if: ${{ github.event.inputs.TOOGLE_QS == true }}
        uses: ./.github/workflows/terraform-plan
        with:
          workspace: qs
      - name: plan
        if: ${{ github.event.inputs.TOOGLE_PROD == true }}
        uses: ./.github/workflows/terraform-plan
        with:
          workspace: prod
  terraform-apply:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: ./.github/workflows/terraform-login
      - name: plan-dev
        if: ${{ github.event.inputs.TOOGLE_DEV == true }}
        uses: ./.github/workflows/terraform-plan
        with:
          workspace: dev
      - name: plan-qs
        if: ${{ github.event.inputs.TOOGLE_QS == true }}
        uses: ./.github/workflows/terraform-plan
        with:
          workspace: qs
      - name: plan-prod
        if: ${{ github.event.inputs.TOOGLE_PROD == true }}
        uses: ./.github/workflows/terraform-plan
        with:
          workspace: prod
      - name: apply-dev
        if: (${{ github.event.inputs.TOOGLE_DEV == true }})
        uses: ./.github/workflows/terraform-apply
        with:
          workspace: dev
      - name: apply-qs
        if: (${{ github.event.inputs.TOOGLE_qs == true }})
        uses: ./.github/workflows/terraform-apply
        with:
          workspace: qs
      - name: apply-prod
        if: (${{ github.event.inputs.TOOGLE_PROD == true }})
        uses: ./.github/workflows/terraform-apply
        with:
          workspace: prod
