name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      workspaces:
        type: string
        default: '["default"]'
    secrets:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
      
jobs:

  terraform-validate:
    uses: ./.github/workflows/terraform-check.yml
    with:
      working-directory: ${{ inputs.working-directory }}
    secrets: 
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      

  terraform-plan:
    needs: terraform-validate
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: 
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      