name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      workspaces:
        type: string
        default: '["default"]'
      
jobs:

  calculate-envs:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.calculate.outputs.envs}}
    steps:
      - id: calculate
        run: |
          echo "::set-output name=envs::$input"
        env:
          input: ${{inputs.workspaces}}

  terraform-pre-plan:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/terraform-pre-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
    secrets: inherit

  terraform-plan-pr:
    needs: calculate-envs
    strategy:
      matrix:
        workspace: ${{needs.calculate-envs.outputs.envs}}
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/terraform-plan-pr.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

  terraform-apply:
    if: github.event_name == 'push'
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: prod
    secrets: inherit

