name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      workspaces:
        type: string
        default: '["default"]'
      
jobs:

  terraform-pre-plan:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/terraform-pre-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
    secrets: inherit

  terraform-plan-pr:
    needs: terraform-pre-plan
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

  terraform-plan-before-apply:
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/lab' || github.ref == 'refs/heads/qs')
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

  terraform-apply:
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    needs: terraform-plan-before-apply
    if: github.event_name == 'push'
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

