name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      workspaces:
        type: string
        default: '["default"]'
      
jobs:

  terraform-plan:
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/lab' || github.ref == 'refs/heads/qs')
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

  terraform-apply:
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    needs: terraform-plan
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/lab' || github.ref == 'refs/heads/qs')
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

