name: Docker Build and Push to ECR

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dry run on PR
      run: docker build --progress=plain --platform=linux/arm64 -t test-build .
      working-directory: ${{ inputs.working-directory }}