name: Docker Build and Push to ECR

on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dry run on PR
      run: |
        cd code
        docker build --progress=plain --platform=linux/arm64 -t test-build .