name: Docker-Test

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Dry run on PR
      run: docker build --progress=plain --platform=linux/arm64 -t test-build .
      working-directory: ${{ inputs.working-directory }}