name: validate-terraform
on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory where the terraform files are located"
        required: true
        type: string
        default: "../terraform/"
      workspace:
        description: "The terraform workspace to use"
        required: false
        type: string
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform select Workspace
        run: terraform select-or-create workspace github.event.inputs.workspace

      - name: Terraform Validate
        if: ${{github.event.inputs.workspace !=false}}
        run: terraform validate -var-file=./env/${{ github.event.inputs.workspace }}.tfvars

      - name: Terraform Validate
        if: ${{github.event.inputs.workspace ==false}}
        run: terraform validate -var-file=./env/${{ github.event.inputs.workspace }}.tfvars

