name: Terraform pre-plan

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      workspace:
        description: "The terraform workspace to use"
        required: true
        type: string

jobs:
  terraform-pre-plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: login
        uses: ./.github/workflows/terraform-login.yml

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Lint
        run: terraform fmt -check

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate