name: terraform-apply
description: Actions needed to deploy terraform
inputs:
  working-directory:
    description: "The working directory where the terraform files are located"
    required: true
    default: "../terraform/"
  workspace:
    description: "The terraform workspace to use"
    required: false

runs:
  steps:
    - name: Terraform Plan
      if: ${{env.workspace !=false}}
      run: terraform plan -var-file=./env/${{ github.workspace }}.tfvars

    - name: Terraform Plan Default Workspace
      if: ${{env.workspace ==false}}
      run: terraform plan
